### PR TITLE
Dynamic survey content + style fixes

### LINKED ISSUE #185: Update SurveyPage on Public View according to Figma wireframe
**Description**
- Follow the Figma wireframe (link provided) to update the context for SurveyPage.
- Use JavaScript instead of JSX to maintain coding standards.
- Relocate the SurveyComponent folder to FRONT > SRC > PAGES > PUBLIC > PAGES > SurveyPage.
- Relocate the ReCaptcha file to FRONT > SRC > PAGES > PUBLIC > Components
- Discuss with Dat to confirm if we need to include the test pages.
- Use Material-ui's SX to create CSS and delete the SurveyComponent.module.css file.

**Links**
Material-ui's SX: https://mui.com/system/getting-started/the-sx-prop/
Figma link: https://www.figma.com/file/KbNIbEz1n8R5EVXEQLRSEX/Heat-Pump?node-id=1002-12532&t=hpcnMVa7pdeWtzGO-4

**Note**
If you have design concerns, contact Sumit B. (@S7mitbarua). For content questions, reach out to Katharine Bierce (@kbierce). For coding concerns, contact Thiago Bardini (@thiagobardini) or Dat Nguyen (@Zevez7).

**Ref**: https://github.com/codeforboston/urban-league-heat-pump-accelerator/pull/187

### PR DESCRIPTION
**Pull request by mattdelsordo**
Resolves #185 and #204

Re: the style fixes:
- centered survey buttons
- made survey content dynamic instead of updating the hardcoded questions
- rename .jsx to .js
- not moving SurveyComponent/ReCaptcha since they're shared across the project
- use mui sx instead of css module

### CODE REVIEW

File: frontend/front/src/components/SurveyComponent/HeatPumpTextField.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
+import { Controller, useController } from "react-hook-form";
+import {
+  FormControl,
+  TextField,
+  Select,
+  MenuItem,
+  InputLabel,
+} from "@mui/material";
```
Comment (thiagobardini) [inline frontend/front/src/components/SurveyComponent/HeatPumpTextField.js:8]: Remove `FormControl, Select, MenuItem, InputLabel`.

File: frontend/front/src/components/SurveyComponent/HeatPumpTextField.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+import React, { useCallback, useMemo } from "react";
```
Comment (thiagobardini) [inline frontend/front/src/components/SurveyComponent/HeatPumpTextField.js:9]: Remove `useCallback, useMemo`.

**Review by thiagobardini — APPROVED** [review]
The public view side looks good to me! Thanks, Matt.
