### PR TITLE
Issue 628 - Fix public survey submission

### LINKED ISSUE #628: Unable to submit a public survey visit
Go to https://staging.bostonhpa.org/public/survey and enter a valid non-duplicate address (until issue 625 resolved). Fill out the survey and click Submit.

1. The user is prompted to enable location permissions - I don't think this should be necessary for the public survey.
2. After allowing location permissions, no request is made to the backend but we do see a green "Survey saved" pop-up banner

### PR DESCRIPTION
**Pull request by Andrewy-gh**
- Add lat long params to public survey submission
- Remove location check and saving snackbar for public survey
- Add memory router to survey component tests

Closes #628

### CODE REVIEW

File: frontend/front/src/components/SurveyComponent/SurveyComponent.js [hunk 1]
```diff
@@ -144,22 +151,28 @@ const SurveyComponent = ({
...
-            resolve({ latitude: "not available", longitude: "not available" });
+            resolve({ latitude: crd.latitude, longitude: crd.longitude });
+          },
+          (err) => {
+            if (err.code === 1) {
+              reject({ error_code: err.code, message: err.message });
+            } else {
+              resolve({
+                latitude: "not available",
+                longitude: "not available",
```
Comment (lfilmeyer) [inline frontend/front/src/components/SurveyComponent/SurveyComponent.js:169]: thoughts on sending null instead?

**Review by mzagaja — APPROVED** [review]
